# Generated by Django 4.2.7 on 2023-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('author', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
    ]
